In [1]:
import pandas as pd
import numpy as np
import anndata as ad

# Loading the excelsheet and saving as csv

In [2]:
excel = pd.read_excel('/Users/lukashat/Documents/PhD_Schapiro/Projects/Myeloma_Standal/metadata/Clinical data IMC project_250128.xlsx', sheet_name='main table')

In [ ]:
excel = excel.iloc[:76,:]

In [ ]:
excel

In [ ]:
excel[excel['Cohort'].isin(['UB', 'B'])]

In [ ]:
excel['Cohort'].value_counts()

In [ ]:
adata = ad.read_h5ad('/Users/lukashat/Documents/PhD_Schapiro/Projects/Myeloma_Standal/results/standard/adatas/cells_current_clr_sample_pp.h5ad')

In [ ]:
array = np.array(adata.obs['patient_ID'].unique())
array = np.sort(array)
array

In [ ]:
excel.replace('NaN', np.nan, inplace=True)

In [ ]:
excel.iloc[:, -9:-1] = excel.iloc[:, -9:-1].astype(bool)
excel['Event (Progress) occurred'] = excel['Event (Progress) occurred'].astype(bool)
excel['Event (Death) occurred'] = excel['Event (Death) occurred'].astype(bool)

In [ ]:
excel

In [ ]:
excel['IMC label']

In [ ]:
excel['IMC label'] = excel['IMC label'].astype(str)
excel['IMC label'] = ['IMC' + (x if len(x) >= 2 else '0' + x) for x in excel['IMC label'] if x]
excel

In [ ]:
excel.to_csv('/Users/lukashat/Documents/PhD_Schapiro/Projects/Myeloma_Standal/metadata/metadata.csv', index=False)

# Same for Treatment excel table

In [63]:
treat = pd.read_excel('/Users/lukashat/Documents/PhD_Schapiro/Projects/Myeloma_Standal/metadata/Treatment related to PFS_251021.xlsx')
adata = ad.read_h5ad("/Users/lukashat/Documents/PhD_Schapiro/Projects/Myeloma_Standal/results/standard/adatas/cells_final.h5ad")

In [64]:
treat = treat.iloc[:63,:7]
treat

,IMC ID,long or short,PFS time,ASCT (yes/no),IMiDs based (yes/no),VCD (yes/no),Treatment line full information
0,1,long_PFS,1766.0,no,yes,no,"Revlimid, Dexamethason"
1,7,long_PFS,1448.0,no,yes,no,"Alkeran, Prednisolon, Revlimid"
2,8,long_PFS,833.0,no,yes,no,"Melfalan, Prednisolon, Thalidomid"
3,9,long_PFS,1337.0,yes,no,yes,Radiation therapy (Melfalan i 2013)
4,12,short_PFS,258.0,no,no,yes,"Bortezomib, Cyklofosfamid, Dexametason (VCD)"
...,...,...,...,...,...,...,...
58,90.1,long_PFS,1536.0,yes,no,yes,"Bortezomib, Cyklofosfamid, Dexametason (VCD)"
59,92,long_PFS,6033.0,yes,no,yes,"Cyklofosfamid, Dexametason (Cd)"
60,93,long_PFS,2375.0,no,yes,no,"Melfalan, Thalidomid, Prednisolon (MTp)"
61,95,long_PFS,1966.0,yes,no,yes,"Bortezomib, Cyklofosfamid, Dexametason (VCD)"
62,96,short_PFS,600.0,no,no,yes,"Melfalan, Prednisolon (Mp) / Bortezomib"

In [65]:
treat['IMC ID'] = treat['IMC ID'].astype(str)
treat['IMC ID'] = ['IMC' + (x if len(x) >= 2 else '0' + x) for x in treat['IMC ID']]
treat

,IMC ID,long or short,PFS time,ASCT (yes/no),IMiDs based (yes/no),VCD (yes/no),Treatment line full information
0,IMC01,long_PFS,1766.0,no,yes,no,"Revlimid, Dexamethason"
1,IMC07,long_PFS,1448.0,no,yes,no,"Alkeran, Prednisolon, Revlimid"
2,IMC08,long_PFS,833.0,no,yes,no,"Melfalan, Prednisolon, Thalidomid"
3,IMC09,long_PFS,1337.0,yes,no,yes,Radiation therapy (Melfalan i 2013)
4,IMC12,short_PFS,258.0,no,no,yes,"Bortezomib, Cyklofosfamid, Dexametason (VCD)"
...,...,...,...,...,...,...,...
58,IMC90.1,long_PFS,1536.0,yes,no,yes,"Bortezomib, Cyklofosfamid, Dexametason (VCD)"
59,IMC92,long_PFS,6033.0,yes,no,yes,"Cyklofosfamid, Dexametason (Cd)"
60,IMC93,long_PFS,2375.0,no,yes,no,"Melfalan, Thalidomid, Prednisolon (MTp)"
61,IMC95,long_PFS,1966.0,yes,no,yes,"Bortezomib, Cyklofosfamid, Dexametason (VCD)"
62,IMC96,short_PFS,600.0,no,no,yes,"Melfalan, Prednisolon (Mp) / Bortezomib"

In [38]:
treat['IMC ID'].nunique()

63

In [17]:
adata.obs['patient_ID'].unique()

['IMC77', 'IMC03', 'IMC04', 'IMC72', 'IMC12', ..., 'IMC87-1', 'IMC41', 'IMC53', 'IMC47', 'IMC83']
Length: 76
Categories (76, object): ['IMC01', 'IMC02', 'IMC03', 'IMC04', ..., 'IMC92', 'IMC93', 'IMC95', 'IMC96']

In [28]:
adata[adata.obs['patient_ID'].str.startswith('IMC40')].obs['patient_ID'].unique()

['IMC40-1']
Categories (1, object): ['IMC40-1']

In [66]:
md = pd.read_csv('/Users/lukashat/Documents/PhD_Schapiro/Projects/Myeloma_Standal/metadata/metadata.csv')
md = md[md['Cohort'].isin(['B', 'UB'])]
md = md.dropna(subset=['Days to progression (PFS)']).reset_index(drop=True)
md

,IMC label,Cohort,Gender,Age time of diagnosis,Event (Progress) occurred,Days to progression (PFS),PFS from first time of diagnosis until relapse (days),Event (Death) occurred,OS (days),Short_long PFS (< or > 2 yrs),...,Treatment line 1,Bone disease upon time of diagnosis/biopsy,Bone disease later in disease course,Compression fractures,Fractures ossis longi or ossis plani,>= 1 lesion,>=3 lesions,>=5 lesions,>=10 lesions,Days to progression from noBD/SMM to BD
0,IMC01,UB,Male,67.0,True,1766.0,3424.0,True,3313.0,long_PFS,...,"Revlimid, Dexamethason",False,False,False,False,False,False,False,False,NaN
1,IMC07,UB,Male,66.0,True,1448.0,1766.0,True,2891.0,long_PFS,...,"Alkeran, Prednisolon, Revlimid",False,True,False,True,False,True,False,False,1858.0
2,IMC08,B,Female,65.0,True,833.0,4050.0,True,3733.0,long_PFS,...,"Melfalan, Prednisolon, Thalidomid",True,True,False,False,True,False,False,False,NaN
3,IMC09,B,Male,58.0,True,1337.0,1337.0,True,2062.0,long_PFS,...,"Strålebehandling, (Melfalan i 2013)",True,True,False,True,False,False,True,False,NaN
4,IMC12,UB,Female,79.0,True,258.0,258.0,True,1370.0,short_PFS,...,"Bortezomib, Cyklofosfamid, Dexametason (VCD)",False,True,False,True,False,False,False,False,1235.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,IMC90.1,B,Female,58.0,True,1536.0,1536.0,False,3418.0,long_PFS,...,"Bortezomib, Cyklofosfamid, Dexametason (VCD)",True,True,False,False,True,False,False,False,NaN
59,IMC92,B,Female,54.0,False,6033.0,NaN,False,6033.0,long_PFS,...,"Cyklofosfamid, Dexametason (Cd)",True,True,False,True,False,True,False,False,NaN
60,IMC93,B,Female,71.0,True,2375.0,2375.0,True,3954.0,long_PFS,...,"Melfalan, Thalidomid, Prednisolon (MTp)",True,True,True,True,False,False,False,True,NaN
61,IMC95,B,Female,58.0,True,1966.0,1966.0,True,4847.0,long_PFS,...,"Bortezomib, Cyklofosfamid, Dexametason (VCD)",True,True,True,True,False,False,True,False,NaN
62,IMC96,B,Male,65.0,True,600.0,551.0,True,3772.0,short_PFS,...,"Melfalan, Prednisolon (Mp) / Bortezomib",True,True,False,False,False,True,False,False,NaN

In [42]:
md.dtypes

IMC label                                                 object
Cohort                                                    object
Gender                                                    object
Age time of diagnosis                                    float64
Event (Progress) occurred                                   bool
Days to progression (PFS)                                float64
PFS from first time of diagnosis until relapse (days)    float64
Event (Death) occurred                                      bool
OS (days)                                                float64
Short_long PFS (< or >  2 yrs)                            object
BMI                                                      float64
FISH/(translocations/del)                                 object
R-ISS                                                     object
Treatment line 1                                          object
Bone disease upon time of diagnosis/biopsy                  bool
Bone disease later in disease course                        bool
Compression fractures                                       bool
Fractures ossis  longi or ossis plani                       bool
>= 1 lesion                                                 bool
>=3 lesions                                                 bool
>=5 lesions                                                 bool
>=10 lesions                                                bool
Days to progression from noBD/SMM to BD                  float64
dtype: object

In [67]:
md_ids = md['IMC label'].unique()
treat_ids = treat['IMC ID'].unique()

md_set = set(md_ids)
treat_set = set(treat_ids)

print('Equal as sets:', md_set == treat_set)
print('Equal as arrays (same order):', np.array_equal(md_ids, treat_ids))

Equal as sets: True
Equal as arrays (same order): True

In [68]:
map_cols = ['ASCT (yes/no)', 'IMiDs based (yes/no)', 'VCD (yes/no)']
treat[map_cols] = treat[map_cols].replace({
    'yes': True,
    'no': False,
    'NaN' : np.nan
}).astype('boolean')

/var/folders/ry/jl4ll0zx1l709rh4r7_0cq6r0000gn/T/ipykernel_3296/1226766419.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  treat[map_cols] = treat[map_cols].replace({

In [73]:
treat.dtypes

IMC ID                              object
long or short                       object
PFS time                           float64
ASCT (yes/no)                      boolean
IMiDs based (yes/no)               boolean
VCD (yes/no)                       boolean
Treatment line full information     object
dtype: object

In [70]:
treat.isna().sum()

IMC ID                             0
long or short                      0
PFS time                           0
ASCT (yes/no)                      1
IMiDs based (yes/no)               0
VCD (yes/no)                       0
Treatment line full information    0
dtype: int64

In [71]:
treat

,IMC ID,long or short,PFS time,ASCT (yes/no),IMiDs based (yes/no),VCD (yes/no),Treatment line full information
0,IMC01,long_PFS,1766.0,False,True,False,"Revlimid, Dexamethason"
1,IMC07,long_PFS,1448.0,False,True,False,"Alkeran, Prednisolon, Revlimid"
2,IMC08,long_PFS,833.0,False,True,False,"Melfalan, Prednisolon, Thalidomid"
3,IMC09,long_PFS,1337.0,True,False,True,Radiation therapy (Melfalan i 2013)
4,IMC12,short_PFS,258.0,False,False,True,"Bortezomib, Cyklofosfamid, Dexametason (VCD)"
...,...,...,...,...,...,...,...
58,IMC90.1,long_PFS,1536.0,True,False,True,"Bortezomib, Cyklofosfamid, Dexametason (VCD)"
59,IMC92,long_PFS,6033.0,True,False,True,"Cyklofosfamid, Dexametason (Cd)"
60,IMC93,long_PFS,2375.0,False,True,False,"Melfalan, Thalidomid, Prednisolon (MTp)"
61,IMC95,long_PFS,1966.0,True,False,True,"Bortezomib, Cyklofosfamid, Dexametason (VCD)"
62,IMC96,short_PFS,600.0,False,False,True,"Melfalan, Prednisolon (Mp) / Bortezomib"

In [72]:
treat.to_csv('/Users/lukashat/Documents/PhD_Schapiro/Projects/Myeloma_Standal/metadata/treatment_metadata.csv', index=False)