In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import anndata as ad
import json
from matplotlib.colors import ListedColormap
import matplotlib.patches as mpatches
import os
import re
from scipy.stats import spearmanr, kruskal, ttest_ind
import statsmodels.stats.multitest as smt
import statsmodels.formula.api as smf
import scikit_posthocs as sp
import warnings
import cellcharter as cc
from sklearn.linear_model import LinearRegression
from itertools import combinations
warnings.filterwarnings('ignore')

In [ ]:
extension = 'svg'
save_path = f'/Users/lukashat/Documents/PhD_Schapiro/Projects/Myeloma_Standal/paper/plots/figures/figure_6/{extension}/'
save_path_supp = f'/Users/lukashat/Documents/PhD_Schapiro/Projects/Myeloma_Standal/paper/plots/figures/suppl_figure_6/{extension}/'
plt.rcParams['figure.dpi'] = 100
plt.rcParams['savefig.dpi'] = 300
adata = ad.read_h5ad("/Users/lukashat/Documents/PhD_Schapiro/Projects/Myeloma_Standal/results/standard/adatas/cells_final.h5ad")
with open('/Users/lukashat/Documents/PhD_Schapiro/Projects/Myeloma_Standal/github/myeloma_imc/src/Paper/figure_plots/neighborhood_color_map.json', 'r') as f:
    neighborhood_color_map = json.load(f)
with open('/Users/lukashat/Documents/PhD_Schapiro/Projects/Myeloma_Standal/github/myeloma_imc/src/Paper/figure_plots/phenotype_color_map.json', 'r') as f:
    phenotype_color_map = json.load(f)
with open('/Users/lukashat/Documents/PhD_Schapiro/Projects/Myeloma_Standal/github/myeloma_imc/src/Paper/figure_plots/disease_color_map.json', 'r') as f:
    disease_color_map = json.load(f)
with open('/Users/lukashat/Documents/PhD_Schapiro/Projects/Myeloma_Standal/github/myeloma_imc/src/Paper/figure_plots/disease3_color_map.json', 'r') as f:
    disease3_color_map = json.load(f)
neighborhood_colors = [neighborhood_color_map[cat] for cat in list(adata.obs['cellcharter_CN'].cat.categories)]
neighborhood_colors = ListedColormap(neighborhood_colors)
phenotype_colors = [phenotype_color_map[cat] for cat in list(adata.obs['Phenotype4'].cat.categories)]
phenotype_colors = ListedColormap(phenotype_colors)
disease_colors = [disease_color_map[cat] for cat in list(adata.obs['disease2'].cat.categories)]
disease_colors = ListedColormap(disease_colors)
disease3_colors = [disease3_color_map[cat] for cat in list(adata.obs['disease3'].cat.categories)]
disease3_colors = ListedColormap(disease3_colors)

In [8]:
disease = 'disease3'
disease_mapping = adata.obs[[disease, 'image_ID']].drop_duplicates()
disease_mapping.set_index('image_ID', inplace=True)

In [ ]:
csv = pd.read_csv('/Users/lukashat/Documents/PhD_Schapiro/Projects/Myeloma_Standal/github/myeloma_standal/src/downstream/dirSEA/250326COZI_grouped_immune_normalized.csv')
csv.rename(columns={'Unnamed: 0': 'image_ID'}, inplace=True)
csv['image_ID'] = csv['image_ID'].replace({'TS-373_IMC42_B_ROI_2.csv': 'TS-373_IMC42_B_002.csv'})
csv['disease3'] = csv['image_ID'].map(disease_mapping['disease3'])
disease_order = ['MM', 'SMM', 'MGUS']
csv[disease] = pd.Categorical(csv[disease], 
                                categories=disease_order, 
                                ordered=True)
csv = csv.sort_values(disease)

# A

In [ ]:
targets = ['image_ID', 'Immune cells_Plasma Cells/MM cells']
pattern = '|'.join(map(re.escape, targets))
interactions = csv.filter(regex=pattern, axis=1)
interactions[disease] = interactions['image_ID'].map(disease_mapping[disease])
interactions[disease] = pd.Categorical(interactions[disease], 
                                categories=disease_order, 
                                ordered=True)
interactions = interactions.sort_values(disease)
interactions = interactions.replace([np.inf, -np.inf], np.nan)
interactions

In [ ]:
interactions.dropna(inplace=True)

In [ ]:
interactions.rename(columns={'Immune cells_Plasma Cells/MM cells': 'Immune cells*PCs'}, inplace=True)

In [ ]:
plt.style.use('default')
fig, ax = plt.subplots(figsize=(36, 1))
ax_plot = sns.heatmap(interactions.drop(columns=['image_ID', disease]).T, cmap='coolwarm', center=0, cbar_kws={'label': 'z-score', 'shrink': 1.5, 'aspect': 5, 'pad': 0.07}, ax=ax, vmin=-0.15, vmax=0.15)
disease_colors = [disease3_color_map[d] for d in interactions[disease]]
ax_disease = fig.add_axes([ax.get_position().x0, 
                           ax.get_position().y1 + 0.01, 
                           ax.get_position().width, 
                           0.14])
ax_disease.imshow([disease_colors], 
                aspect='auto',
                extent=[0, len(disease_colors), 0, 1])
ax_disease.set_xticks([])
ax_disease.set_yticks([])
ax_disease.set_xticklabels('')
ax_plot.set_xlabel('')
ax_plot.set_xticklabels('')
ax_plot.set_yticklabels(ax_plot.get_yticklabels(), size=16)
if disease == 'disease3':
        legend_patches = [mpatches.Patch(color=color, label=disease_) 
                        for disease_, color in disease3_color_map.items()]
if disease == 'disease2':
        legend_patches = [mpatches.Patch(color=color, label=disease_) 
                        for disease_, color in disease_color_map.items()]
cbar = ax_plot.collections[0].colorbar
cbar.ax.tick_params(labelsize=16)          # Tick labels
cbar.ax.yaxis.label.set_size(18) 
ax.legend(handles=legend_patches, 
        bbox_to_anchor=(1.0, 1.6),
        framealpha=0.0, 
        loc='upper left',
        title='Disease Cohort',
        title_fontsize=16,
        fontsize=14)
#plt.tight_layout()
plt.savefig(os.path.join(save_path, f'interaction_immune_tumor.{extension}'), bbox_inches='tight')

# B

In [ ]:
fig, ax = plt.subplots(figsize=(6, 5))
sns.kdeplot(data=interactions, x='Immune cells*PCs', hue=disease, palette=disease3_color_map, fill=True, alpha=0.5, linewidth=2, common_norm=False, ax=ax)
ax.set_xlabel('Immune cells*PCs NEP score', fontsize=14)
ax.set_ylabel('Density', fontsize=14)
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
legend = ax.get_legend()
legend.set_title('')
for text in legend.get_texts():
	text.set_fontsize(14)
fig.tight_layout()
plt.savefig(os.path.join(save_path, f'interaction_immune_tumor_density.{extension}'), bbox_inches='tight')

# D

In [ ]:
adata_cc = adata.copy()
cc.gr.connected_components(adata_cc, cluster_key='cellcharter_CN', min_cells=1)
adata_cc = adata_cc[~adata_cc.obs['component'].isna()]

In [ ]:
count = adata_cc.obs['component'].value_counts().to_dict()

if 'shape_component' not in adata_cc.uns:
    adata_cc.uns['shape_component'] = {}
adata_cc.uns['shape_component']['count'] = count
df = pd.DataFrame(adata_cc.uns['shape_component']['count'].items(), columns=['component', 'count'])
df = pd.merge(df, adata_cc.obs[['component', 'image_ID']].drop_duplicates().dropna(), on='component')
df = pd.merge(df, adata_cc.obs[['component', 'cellcharter_CN']].drop_duplicates().dropna(), on='component')
df = pd.merge(df, adata_cc.obs[['component', 'disease3']].drop_duplicates().dropna(), on='component')

counts = adata_cc[~adata_cc.obs['component'].isna()].obs.groupby(['image_ID', 'cellcharter_CN']).size().reset_index(name='total_neighborhood_cells_image')
df = df.merge(counts, on=['image_ID', 'cellcharter_CN'], how='left')

unique_counts = (
    adata_cc.obs.groupby(["image_ID", "cellcharter_CN"])["component"]
    .nunique()
    .reset_index()
    .rename(columns={"component": "unique_components_neighborhood_image"})
)
df = df.merge(unique_counts, on=["image_ID", "cellcharter_CN"], how="left")
df = df[df['cellcharter_CN'] =='PC_OXPHOS']
df2 = df.groupby('image_ID').max('count')

In [ ]:
merged = pd.merge(
    interactions,
    df2,
    left_on='image_ID',
    right_index=True)
merged.dropna(inplace=True)
merged['count'] = np.log(merged['count'])
merged

In [ ]:
plt.style.use('default')
plt.figure(figsize=(5, 5))
sns.scatterplot(
    x='count',
    y='Immune cells*PCs',
    data=merged,
    hue='disease3',
    palette=disease3_color_map,
    legend=False)
sns.regplot(
    x='count',
    y='Immune cells*PCs',
    data=merged,
    scatter=False,
    color='black'
)
# Select 'count' as a DataFrame (2D)
X = merged[['count']]
y = merged['Immune cells*PCs']

model = LinearRegression()
model.fit(X, y)
y_pred = model.predict(X)
r2 = model.score(X, y)
stat, p = spearmanr(merged['count'], merged['Immune cells*PCs'])
plt.text(0.01, 0.1, f'Spearman $\\rho$ = {stat:.2f}, \nSpearman $p$ = {p:.2e} \n$R^2$ = {r2:.2f}', transform=plt.gca().transAxes, fontsize=12)
plt.xlabel(r'$\log(\text{counts})$ of max.' + '\n' + r'PC_OXPHOS component size', fontsize=14)
plt.ylabel('Immune cells*PCs NEP score', fontsize=14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.tight_layout()
plt.savefig(os.path.join(save_path, f'PC_immune_interaction_pc_oxphos_component_correlation.{extension}'))

# E-G

In [ ]:

# markers = ['GranzymeK']
# celltype = 'CD8 T'
# cell = adata[adata.obs['Phenotype4'] == celltype]
# cell_subset = cell[cell.obs[f'cellcharter_CN'].isin(['PC_OXPHOS', 'PC_MYELOID', 'HIF1A_IMMUNE', 'ADAPTIVE_IMMUNE'])].copy()
# df = cell_subset.to_df()
# df['cellcharter_CN'] = cell_subset.obs['cellcharter_CN']
# df['cellcharter_CN'] = pd.Categorical(df['cellcharter_CN'], 
#                                      categories=['ADAPTIVE_IMMUNE', 'HIF1A_IMMUNE', 'PC_MYELOID', 'PC_OXPHOS'], 
#                                      ordered=True)
# df['patient_ID'] = cell_subset.obs['patient_ID']
# pairwise_pval_frames = {}
# with plt.rc_context({"figure.figsize": (3, 3)}):
#     for marker in markers:
#         axes = sns.violinplot(x='cellcharter_CN', y=marker, data=df,
#                               #hue = disease,
#                               #hue_order=disease_order,
#                               palette=neighborhood_color_map,
#                               scale='width',
#                               inner='box')
#         axes.set_title(f'')
        
#         # Get current y-axis limits
#         ymin, ymax = axes.get_ylim()
#         # Set new y-axis limits with 0.5 added to the max limit
#         axes.set_ylim(0, 1.4)
#         axes.set_xticklabels(axes.get_xticklabels(), rotation=90, fontsize=12)
#         axes.set_yticklabels(axes.get_yticklabels(), fontsize=12)
#         axes.set_ylabel(f'{marker} (CLR)', fontsize=14)
#         axes.set_xlabel('')
        
        
#         fig = axes.figure
#         fig.savefig(os.path.join(save_path, f'violin_{celltype}_{marker}_per_image_neighborhoods.{extension}'), 
#                     dpi=300, 
#                     bbox_inches='tight',
#                     pad_inches=0.1)
#         model = smf.mixedlm(f"Q('{marker}') ~ C(cellcharter_CN)", 
#                     data=df, 
#                     groups=df["patient_ID"],
#                     re_formula="~C(cellcharter_CN)")
#         result = model.fit()

#         # Get contrasts
#         fixed_fx_names = result.model.exog_names
#         num_params = len(fixed_fx_names)
    
   
#         all_categories = df['cellcharter_CN'].unique()
        
#         pvals = []
#         pairs = []
        
        
#         for cat1, cat2 in combinations(all_categories, 2):
            
            
#             name1 = f"C(cellcharter_CN)[T.{cat1}]"
#             name2 = f"C(cellcharter_CN)[T.{cat2}]"
            
            
#             contrast = np.zeros(num_params)
            
            
#             if name1 in fixed_fx_names:
#                 contrast[fixed_fx_names.index(name1)] = 1
            
#             if name2 in fixed_fx_names:
#                 contrast[fixed_fx_names.index(name2)] = -1
                
           
#             contrast_matrix = contrast.reshape(1, -1)
                
            
#             t_test_res = result.t_test(contrast_matrix)
#             p_val = t_test_res.pvalue.item()
            
#             pairs.append(f"{cat1} - {cat2}")
#             pvals.append(p_val)

#         # Multiple testing
#         reject, pvals_corr, _, _ = smt.multipletests(pvals, method='hs')
        
#         results_df = pd.DataFrame({
#             'Pair': pairs,
#             'pvalue': pvals,
#             'pvalue_adj': pvals_corr,
#             'Significant': reject
#         })
        
#         pairwise_pval_frames[marker] = results_df
        

#         plt.close(fig)

In [ ]:

# pd.concat(pairwise_pval_frames, names=['marker', 'idx']).reset_index(level='idx', drop=True).reset_index()

In [ ]:
# markers = ['HLA-DR', 'IDO']
# celltype = 'DCs'
# cell = adata[adata.obs['Phenotype4'] == celltype]
# cell_subset = cell[cell.obs[f'cellcharter_CN'].isin(['PC_OXPHOS', 'PC_MYELOID', 'HIF1A_IMMUNE', 'ADAPTIVE_IMMUNE'])].copy()
# df = cell_subset.to_df()
# df['cellcharter_CN'] = cell_subset.obs['cellcharter_CN']
# df['cellcharter_CN'] = pd.Categorical(df['cellcharter_CN'], 
#                                      categories=['ADAPTIVE_IMMUNE', 'HIF1A_IMMUNE', 'PC_MYELOID', 'PC_OXPHOS'], 
#                                      ordered=True)
# df['patient_ID'] = cell_subset.obs['patient_ID']
# pairwise_pval_frames = {}
# with plt.rc_context({"figure.figsize": (3, 3)}):
#     for marker in markers:
#         axes = sns.violinplot(x='cellcharter_CN', y=marker, data=df,
#                               #hue = disease,
#                               #hue_order=disease_order,
#                               palette=neighborhood_color_map,
#                               scale='width',
#                               inner='box')
#         axes.set_title(f'')
        
#         # Get current y-axis limits
#         ymin, ymax = axes.get_ylim()
#         # Set new y-axis limits with 0.5 added to the max limit
#         axes.set_ylim(0, 1.4)
#         axes.set_xticklabels(axes.get_xticklabels(), rotation=90, fontsize=12)
#         axes.set_yticklabels(axes.get_yticklabels(), fontsize=12)
#         axes.set_ylabel(f'{marker} (CLR)', fontsize=14)
#         axes.set_xlabel('')
        
        
#         fig = axes.figure
#         fig.savefig(os.path.join(save_path, f'violin_{celltype}_{marker}_per_image_neighborhoods.{extension}'), 
#                     dpi=300, 
#                     bbox_inches='tight',
#                     pad_inches=0.1)
#         model = smf.mixedlm(f"Q('{marker}') ~ C(cellcharter_CN)", 
#                     data=df, 
#                     groups=df["patient_ID"],
#                     re_formula="~C(cellcharter_CN)")
#         result = model.fit()

        
#         fixed_fx_names = result.model.exog_names
#         num_params = len(fixed_fx_names)
    
#     #
#         all_categories = df['cellcharter_CN'].unique()
        
#         pvals = []
#         pairs = []
        
        
#         for cat1, cat2 in combinations(all_categories, 2):
            
            
#             name1 = f"C(cellcharter_CN)[T.{cat1}]"
#             name2 = f"C(cellcharter_CN)[T.{cat2}]"
            
           
#             contrast = np.zeros(num_params)
            
            
#             if name1 in fixed_fx_names:
#                 contrast[fixed_fx_names.index(name1)] = 1
            
#             if name2 in fixed_fx_names:
#                 contrast[fixed_fx_names.index(name2)] = -1
                
            
#             contrast_matrix = contrast.reshape(1, -1)
                
            
#             t_test_res = result.t_test(contrast_matrix)
#             p_val = t_test_res.pvalue.item()
            
#             pairs.append(f"{cat1} - {cat2}")
#             pvals.append(p_val)

        
#         reject, pvals_corr, _, _ = smt.multipletests(pvals, method='holm')
        
#         results_df = pd.DataFrame({
#             'Pair': pairs,
#             'pvalue': pvals,
#             'pvalue_adj': pvals_corr,
#             'Significant': reject
#         })
        
#         pairwise_pval_frames[marker] = results_df
        

#         plt.close(fig)

In [ ]:

# pd.concat(pairwise_pval_frames, names=['marker', 'idx']).reset_index(level='idx', drop=True).reset_index()

In [ ]:
# markers = ['HLA-DR', 'IDO']
# celltype = 'HLA-DR+ Macs/monos'
# cell = adata[adata.obs['Phenotype4'] == celltype]
# cell_subset = cell[cell.obs[f'cellcharter_CN'].isin(['PC_OXPHOS', 'PC_MYELOID', 'HIF1A_IMMUNE', 'ADAPTIVE_IMMUNE'])].copy()
# df = cell_subset.to_df()
# df['cellcharter_CN'] = cell_subset.obs['cellcharter_CN']
# df['cellcharter_CN'] = pd.Categorical(df['cellcharter_CN'], 
#                                      categories=['ADAPTIVE_IMMUNE', 'HIF1A_IMMUNE', 'PC_MYELOID', 'PC_OXPHOS'], 
#                                      ordered=True)
# df['patient_ID'] = cell_subset.obs['patient_ID']
# pairwise_pval_frames = {}
# with plt.rc_context({"figure.figsize": (3, 3)}):
#     for marker in markers:
#         axes = sns.violinplot(x='cellcharter_CN', y=marker, data=df,
#                               #hue = disease,
#                               #hue_order=disease_order,
#                               palette=neighborhood_color_map,
#                               scale='width',
#                               inner='box')
#         axes.set_title(f'')
        
#         # Get current y-axis limits
#         ymin, ymax = axes.get_ylim()
#         # Set new y-axis limits with 0.5 added to the max limit
#         axes.set_ylim(0, 1.4)
#         axes.set_xticklabels(axes.get_xticklabels(), rotation=90, fontsize=12)
#         axes.set_yticklabels(axes.get_yticklabels(), fontsize=12)
#         axes.set_ylabel(f'{marker} (CLR)', fontsize=14)
#         axes.set_xlabel('')
        
        
#         fig = axes.figure
#         fig.savefig(os.path.join(save_path, f'violin_HLA-DR+_Macs_monos_{marker}_per_image_neighborhoods.{extension}'), 
#                     dpi=300, 
#                     bbox_inches='tight',
#                     pad_inches=0.1)
#         model = smf.mixedlm(f"Q('{marker}') ~ C(cellcharter_CN)", 
#                     data=df, 
#                     groups=df["patient_ID"],
#                     re_formula="~1+C(cellcharter_CN)")
#         result = model.fit()

        
#         fixed_fx_names = result.model.exog_names
#         num_params = len(fixed_fx_names)
    
    
#         all_categories = df['cellcharter_CN'].unique()
        
#         pvals = []
#         pairs = []
        
        
#         for cat1, cat2 in combinations(all_categories, 2):
            
            
#             name1 = f"C(cellcharter_CN)[T.{cat1}]"
#             name2 = f"C(cellcharter_CN)[T.{cat2}]"
            
            
#             contrast = np.zeros(num_params)
            
            
#             if name1 in fixed_fx_names:
#                 contrast[fixed_fx_names.index(name1)] = 1
            
#             if name2 in fixed_fx_names:
#                 contrast[fixed_fx_names.index(name2)] = -1
                
            
#             contrast_matrix = contrast.reshape(1, -1)
                
            
#             t_test_res = result.t_test(contrast_matrix)
#             p_val = t_test_res.pvalue.item()
            
#             pairs.append(f"{cat1} - {cat2}")
#             pvals.append(p_val)

        
#         reject, pvals_corr, _, _ = smt.multipletests(pvals, method='bonferroni')
        
#         results_df = pd.DataFrame({
#             'Pair': pairs,
#             'pvalue': pvals,
#             'pvalue_adj': pvals_corr,
#             'Significant': reject
#         })
        
#         pairwise_pval_frames[marker] = results_df
        

#         plt.close(fig)

In [ ]:

# pd.concat(pairwise_pval_frames, names=['marker', 'idx']).reset_index(level='idx', drop=True).reset_index()

In [9]:
markers = ['HLA-DR', 'IDO']
celltype = 'DCs'
cell = adata[adata.obs['Phenotype4'] == celltype]
cell_subset = cell[cell.obs[f'cellcharter_CN'].isin(['PC_OXPHOS', 'PC_MYELOID', 'HIF1A_IMMUNE', 'ADAPTIVE_IMMUNE'])].copy()
df = cell_subset.to_df()
df['cellcharter_CN'] = cell_subset.obs['cellcharter_CN']
df['image_ID'] = cell_subset.obs['image_ID']
df2 = df.groupby(['cellcharter_CN', 'image_ID']).median().reset_index().dropna()
df2[disease] = df2['image_ID'].map(disease_mapping[disease])
with plt.rc_context({"figure.figsize": (3, 3)}):
    for marker in markers:
        axes = sns.violinplot(x='cellcharter_CN', y=marker, data=df2,
                              #hue = disease,
                              #hue_order=disease_order,
                              palette=neighborhood_color_map,
                              scale='width',
                              inner='box')
        axes.set_title(f'')
        
        # Get current y-axis limits
        ymin, ymax = axes.get_ylim()
        # Set new y-axis limits with 0.5 added to the max limit
        axes.set_ylim(0, 1.1)
        axes.set_xticklabels(axes.get_xticklabels(), rotation=90, fontsize=12)
        axes.set_yticklabels(axes.get_yticklabels(), fontsize=12)
        axes.set_ylabel(f'{marker} (CLR)', fontsize=14)
        axes.set_xlabel('')
        
        
        fig = axes.figure
        fig.savefig(os.path.join(save_path, f'violin_{celltype}_{marker}_per_image_neighborhoods.{extension}'), 
                    dpi=300, 
                    bbox_inches='tight',
                    pad_inches=0.1)
        plt.close(fig)

In [12]:
target_neighborhoods = ['PC_OXPHOS', 'PC_MYELOID', 'HIF1A_IMMUNE', 'ADAPTIVE_IMMUNE']
filtered_df = df2[df2['cellcharter_CN'].isin(target_neighborhoods)]
groups = [group['HLA-DR'].values for _, group in filtered_df.groupby('cellcharter_CN')]
kruskal_result = kruskal(*groups)
print(f"Kruskal-Wallis H-stat: {kruskal_result.statistic:.3f}, p-val: {kruskal_result.pvalue:.4f}")

dunn_results = sp.posthoc_dunn(
    filtered_df, 
    val_col='HLA-DR',
    group_col='cellcharter_CN',
    p_adjust='bonferroni'
)
print("\nDunn's posthoc results:")
dunn_results

Kruskal-Wallis H-stat: 65.578, p-val: 0.0000

Dunn's posthoc results:

                 ADAPTIVE_IMMUNE  HIF1A_IMMUNE  PC_MYELOID  PC_OXPHOS
ADAPTIVE_IMMUNE     1.000000e+00  8.837758e-15    0.000013   0.000001
HIF1A_IMMUNE        8.837758e-15  1.000000e+00    0.006639   0.150140
PC_MYELOID          1.283966e-05  6.638792e-03    1.000000   1.000000
PC_OXPHOS           1.012100e-06  1.501404e-01    1.000000   1.000000

In [13]:
target_neighborhoods = ['PC_OXPHOS', 'PC_MYELOID', 'HIF1A_IMMUNE', 'ADAPTIVE_IMMUNE']
filtered_df = df2[df2['cellcharter_CN'].isin(target_neighborhoods)]
groups = [group['IDO'].values for _, group in filtered_df.groupby('cellcharter_CN')]
kruskal_result = kruskal(*groups)
print(f"Kruskal-Wallis H-stat: {kruskal_result.statistic:.3f}, p-val: {kruskal_result.pvalue:.4f}")

dunn_results = sp.posthoc_dunn(
    filtered_df, 
    val_col='IDO',
    group_col='cellcharter_CN',
    p_adjust='bonferroni'
)
print("\nDunn's posthoc results:")
dunn_results

Kruskal-Wallis H-stat: 46.427, p-val: 0.0000

Dunn's posthoc results:

                 ADAPTIVE_IMMUNE  HIF1A_IMMUNE    PC_MYELOID  PC_OXPHOS
ADAPTIVE_IMMUNE     1.000000e+00      0.000033  2.309418e-10   0.000027
HIF1A_IMMUNE        3.322614e-05      1.000000  1.472878e-01   1.000000
PC_MYELOID          2.309418e-10      0.147288  1.000000e+00   0.564230
PC_OXPHOS           2.719751e-05      1.000000  5.642299e-01   1.000000

In [15]:
target_neighborhoods = ['PC_OXPHOS', 'PC_MYELOID', 'HIF1A_IMMUNE', 'ADAPTIVE_IMMUNE']
pval_frames = {}
for celltype in ['DCs', 'HLA-DR+ Macs/monos', 'CD8 T']:
    if celltype in ['DCs', 'HLA-DR+ Macs/monos']:
        markers = ['HLA-DR', 'IDO']
    elif celltype == 'CD8 T':
        markers = ['GranzymeK']
    cell = adata[adata.obs['Phenotype4'] == celltype]
    cell_subset = cell[cell.obs[f'cellcharter_CN'].isin(['PC_OXPHOS', 'PC_MYELOID', 'HIF1A_IMMUNE', 'ADAPTIVE_IMMUNE'])].copy()
    df = cell_subset.to_df()
    df['cellcharter_CN'] = cell_subset.obs['cellcharter_CN']
    df['image_ID'] = cell_subset.obs['image_ID']
    df2 = df.groupby(['cellcharter_CN', 'image_ID']).median().reset_index().dropna()
    df2[disease] = df2['image_ID'].map(disease_mapping[disease])
    with plt.rc_context({"figure.figsize": (3, 3)}):
        for marker in markers:
            axes = sns.violinplot(x='cellcharter_CN', y=marker, data=df2,
                                #hue = disease,
                                #hue_order=disease_order,
                                palette=neighborhood_color_map,
                                scale='width',
                                inner='box')
            axes.set_title(f'')
            
            # Get current y-axis limits
            ymin, ymax = axes.get_ylim()
            # Set new y-axis limits with 0.5 added to the max limit
            axes.set_ylim(0, 1.1)
            axes.set_xticklabels(axes.get_xticklabels(), rotation=90, fontsize=12)
            axes.set_yticklabels(axes.get_yticklabels(), fontsize=12)
            axes.set_ylabel(f'{marker} (CLR)', fontsize=14)
            axes.set_xlabel('')
            
            
            fig = axes.figure
            if celltype == 'HLA-DR+ Macs/monos':
                fig.savefig(os.path.join(save_path, f'violin_HLA-DR+_Macs_monos_{marker}_per_image_neighborhoods.{extension}'), 
                        dpi=300, 
                        bbox_inches='tight',
                        pad_inches=0.1)
            else:
                fig.savefig(os.path.join(save_path, f'violin_{celltype}_{marker}_per_image_neighborhoods.{extension}'), 
                            dpi=300, 
                            bbox_inches='tight',
                            pad_inches=0.1)
            plt.close(fig)
            
            filtered_df = df2[df2['cellcharter_CN'].isin(target_neighborhoods)]
            groups = [group[marker].values for _, group in filtered_df.groupby('cellcharter_CN')]
            kruskal_result = kruskal(*groups)
            print(f"Kruskal-Wallis H-stat: {kruskal_result.statistic:.3f}, p-val: {kruskal_result.pvalue:.4f}")

            if kruskal_result.pvalue < 0.05:
                dunn_results = sp.posthoc_dunn(
                    filtered_df, 
                    val_col=marker,
                    group_col='cellcharter_CN',
                    p_adjust='bonferroni'
                )
                pval_frames[(celltype, marker)] = dunn_results

Kruskal-Wallis H-stat: 65.578, p-val: 0.0000
Kruskal-Wallis H-stat: 46.427, p-val: 0.0000
Kruskal-Wallis H-stat: 53.550, p-val: 0.0000
Kruskal-Wallis H-stat: 38.894, p-val: 0.0000
Kruskal-Wallis H-stat: 67.131, p-val: 0.0000

In [16]:
pval_frames

{('DCs',
  'HLA-DR'):                  ADAPTIVE_IMMUNE  HIF1A_IMMUNE  PC_MYELOID  PC_OXPHOS
 ADAPTIVE_IMMUNE     1.000000e+00  8.837758e-15    0.000013   0.000001
 HIF1A_IMMUNE        8.837758e-15  1.000000e+00    0.006639   0.150140
 PC_MYELOID          1.283966e-05  6.638792e-03    1.000000   1.000000
 PC_OXPHOS           1.012100e-06  1.501404e-01    1.000000   1.000000,
 ('DCs',
  'IDO'):                  ADAPTIVE_IMMUNE  HIF1A_IMMUNE    PC_MYELOID  PC_OXPHOS
 ADAPTIVE_IMMUNE     1.000000e+00      0.000033  2.309418e-10   0.000027
 HIF1A_IMMUNE        3.322614e-05      1.000000  1.472878e-01   1.000000
 PC_MYELOID          2.309418e-10      0.147288  1.000000e+00   0.564230
 PC_OXPHOS           2.719751e-05      1.000000  5.642299e-01   1.000000,
 ('HLA-DR+ Macs/monos',
  'HLA-DR'):                  ADAPTIVE_IMMUNE  HIF1A_IMMUNE  PC_MYELOID  PC_OXPHOS
 ADAPTIVE_IMMUNE     1.000000e+00  5.828023e-12    0.000054   0.032375
 HIF1A_IMMUNE        5.828023e-12  1.000000e+00    0.039507   0.000094
 PC_MYELOID          5.449134e-05  3.950716e-02    1.000000   0.621799
 PC_OXPHOS           3.237475e-02  9.382706e-05    0.621799   1.000000,
 ('HLA-DR+ Macs/monos',
  'IDO'):                  ADAPTIVE_IMMUNE  HIF1A_IMMUNE    PC_MYELOID     PC_OXPHOS
 ADAPTIVE_IMMUNE     1.000000e+00      0.001730  9.017188e-07  1.666937e-07
 HIF1A_IMMUNE        1.730190e-03      1.000000  5.911556e-01  2.766413e-01
 PC_MYELOID          9.017188e-07      0.591156  1.000000e+00  1.000000e+00
 PC_OXPHOS           1.666937e-07      0.276641  1.000000e+00  1.000000e+00,
 ('CD8 T',
  'GranzymeK'):                  ADAPTIVE_IMMUNE  HIF1A_IMMUNE    PC_MYELOID     PC_OXPHOS
 ADAPTIVE_IMMUNE     1.000000e+00      1.000000  2.827583e-09  4.398984e-10
 HIF1A_IMMUNE        1.000000e+00      1.000000  5.559552e-06  1.107659e-06
 PC_MYELOID          2.827583e-09      0.000006  1.000000e+00  1.000000e+00
 PC_OXPHOS           4.398984e-10      0.000001  1.000000e+00  1.000000e+00}

# Suppl

In [ ]:
csv = pd.read_csv('/Users/lukashat/Documents/PhD_Schapiro/Projects/Myeloma_Standal/github/myeloma_standal/src/downstream/dirSEA/250326COZI_phenotype4_normalized.csv')
csv.rename(columns={'Unnamed: 0': 'image_ID'}, inplace=True)
csv['image_ID'] = csv['image_ID'].replace({'TS-373_IMC42_B_ROI_2.csv': 'TS-373_IMC42_B_002.csv'})
csv['disease3'] = csv['image_ID'].map(disease_mapping['disease3'])
disease_order = ['MM', 'SMM', 'MGUS']
csv[disease] = pd.Categorical(csv[disease], 
                                categories=disease_order, 
                                ordered=True)
csv = csv.sort_values(disease)

In [ ]:
csv

In [ ]:
targets = ['image_ID', 'CD8+Tcells_Plasma Cells/MM cells', 'CD4+Tcells_Plasma Cells/MM cells', 'Dendritic Cells_Plasma Cells/MM cells', 'activated Macrophages/Monocytes_Plasma Cells/MM cells', 'Neutrophils_Plasma Cells/MM cells',
           'Macrophages/Monocytes_Plasma Cells/MM cells']
pattern = '|'.join(map(re.escape, targets))
interactions = csv.filter(regex=pattern, axis=1)
interactions[disease] = interactions['image_ID'].map(disease_mapping[disease])
interactions[disease] = pd.Categorical(interactions[disease], 
                                categories=disease_order, 
                                ordered=True)
interactions = interactions.sort_values(disease)
interactions = interactions.replace([np.inf, -np.inf], np.nan)
interactions

In [ ]:
interactions.rename(columns={'CD8+Tcells_Plasma Cells/MM cells': 'CD8 Tcells*PCs','CD4+Tcells_Plasma Cells/MM cells': 'CD4 Tcells*PCs', 'Dendritic Cells_Plasma Cells/MM cells': 'DCs*PCs',
                             'activated Macrophages/Monocytes_Plasma Cells/MM cells': 'HLA-DR+ Macs/monos*PCs', 'Neutrophils_Plasma Cells/MM cells': 'Neutrophils*PCs', 'Macrophages/Monocytes_Plasma Cells/MM cells': 'Macs/monos*PCs'}, inplace=True)
interactions

In [ ]:
plt.style.use('default')
fig, ax = plt.subplots(figsize=(36, 2))
ax_plot = sns.heatmap(interactions.drop(columns=['image_ID', disease]).T, cmap='coolwarm', center=0, cbar_kws={'label': 'z-score', 'shrink': 1.4, 'aspect': 5, 'pad': 0.07}, ax=ax, vmin=-0.15, vmax=0.15)
disease_colors = [disease3_color_map[d] for d in interactions[disease]]
ax_disease = fig.add_axes([ax.get_position().x0, 
                           ax.get_position().y1 + 0.01, 
                           ax.get_position().width, 
                           0.14])
ax_disease.imshow([disease_colors], 
                aspect='auto',
                extent=[0, len(disease_colors), 0, 1])
ax_disease.set_xticks([])
ax_disease.set_yticks([])
ax_disease.set_xticklabels('')
ax_plot.set_xlabel('')
ax_plot.set_xticklabels('')
ax_plot.set_yticklabels(ax_plot.get_yticklabels(), size=16)
if disease == 'disease3':
        legend_patches = [mpatches.Patch(color=color, label=disease_) 
                        for disease_, color in disease3_color_map.items()]
if disease == 'disease2':
        legend_patches = [mpatches.Patch(color=color, label=disease_) 
                        for disease_, color in disease_color_map.items()]
cbar = ax_plot.collections[0].colorbar
cbar.ax.tick_params(labelsize=16)          # Tick labels
cbar.ax.yaxis.label.set_size(18) 
ax.legend(handles=legend_patches, 
        bbox_to_anchor=(1.0, 1.3),
        framealpha=0.0, 
        loc='upper left',
        title='Disease',
        title_fontsize=16,
        fontsize=14)
#plt.tight_layout()
plt.savefig(os.path.join(save_path_supp, f'interaction_all_immune_tumor.{extension}'), bbox_inches='tight')